### Script SQL : Munity.sql
sql
CREATE DATABASE IF NOT EXISTS Munity;

USE Munity;

CREATE TABLE IF NOT EXISTS members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);